- 👋 Hi, I’m @AkankshaSirohi
- 👀 I’m interested in looking for talent...
- 🌱 I’m currently learning HR...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me akanksha@militarytocorp.com...

<!---
AkankshaSirohi/AkankshaSirohi is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
